name: $(SemVer)

variables:
  BuildConfiguration: Release
  SemVer: $[ variables['Build.SourceBranchName'] ]
  CommitId: $(Build.SourceVersion)

trigger:
  batch: true
  branches:
    include:
    - refs/tags/*

pr: none

pool:
  vmImage: ubuntu-18.04

stages:
- template: azure-templates/stage-build.yml
- template: azure-templates/stage-deploy.yml