version: "3"
services:
  nats:
    image: "nats"
    ports:
      - "4222:4222"
  nats-auth:
    image: "nats"
    ports:
      - "4223:4222"
    environment:
      - MyNats_credentials__user
      - MyNats_credentials__pass
    command: "-c /nats_config/auth.config"
    volumes:
      - ./nats_config:/nats_config
  nats-tls:
    image: "nats"
    ports:
      - "4224:4222"
    command: "-c /nats_config/tls.config"
    volumes:
      - ./nats_config:/nats_config